# Generated by Django 5.2.7 on 2026-03-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('EnrollmentID', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه ثبت\u200cنام')),
                ('EnrolledAt', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت\u200cنام')),
                ('Grade', models.CharField(blank=True, max_length=5, null=True, verbose_name='نمره نهایی')),
            ],
            options={
                'db_table': 'Enrollments',
                'managed': False,
            },
        ),
    ]
