# Generated by Django 5.2.7 on 2026-03-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه کاربر')),
                ('Username', models.CharField(max_length=150, unique=True, verbose_name='نام کاربری')),
                ('FirstName', models.CharField(max_length=100, verbose_name='نام')),
                ('LastName', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('PasswordHash', models.CharField(max_length=255, verbose_name='رمز عبور (هش شده)')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('PhoneNumber', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('IsLoggedIn', models.BooleanField(default=False, verbose_name='وضعیت ورود')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
