# Generated by Django 5.2.7 on 2026-03-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('OptionID', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه گزینه')),
                ('OptionText', models.TextField(blank=True, null=True, verbose_name='متن گزینه')),
                ('OptionLabel', models.CharField(max_length=100, verbose_name='برچسب گزینه')),
                ('IsCorrect', models.BooleanField(default=False, verbose_name='صحیح است')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'گزینه ها',
                'db_table': 'QuestionOptions',
                'managed': False,
            },
        ),
    ]
