# Generated by Django 5.2.7 on 2026-03-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionOptions', '0002_auto_20260318_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoption',
            options={'managed': False},
        ),
    ]
