# Generated by Django 5.2.7 on 2026-03-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه لاگ')),
                ('ScreenWidth', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عرض پنجره مررگر')),
                ('ScreenHeight', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ارتفاع پنجره مررگر')),
                ('ChangeTime', models.DateTimeField(auto_now_add=True, verbose_name='زمان تغییر')),
            ],
            options={
                'verbose_name': 'لاگ رزولوشن',
                'verbose_name_plural': 'لاگ های رزولوشن',
                'db_table': 'ResolutionLogs',
                'managed': False,
            },
        ),
    ]
