# Generated by Django 5.2.7 on 2026-03-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه سوال')),
                ('QuestionText', models.TextField(verbose_name='متن سوال')),
                ('QuestionType', models.CharField(choices=[('multiple_choice', 'چند گزینه\u200cای'), ('descriptive', 'تشریحی')], default='multiple_choice', max_length=20, verbose_name='نوع سوال')),
                ('Score', models.DecimalField(decimal_places=2, help_text='نمره این سوال', max_digits=5, verbose_name='نمره')),
                ('CorrectAnswer', models.PositiveSmallIntegerField(blank=True, help_text='شماره گزینه صحیح (1 برای گزینه اول، 2 برای دوم و ...)', verbose_name='پاسخ صحیح')),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
    ]
