# Generated by Django 5.2.7 on 2026-03-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_auto_20260318_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'managed': False},
        ),
    ]
