# Generated by Django 5.2.7 on 2026-04-20 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'managed': False, 'ordering': ['Order']},
        ),
    ]
