# Generated by Django 5.2.7 on 2026-03-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه پاسخ')),
                ('AnswerText', models.TextField(blank=True, null=True, verbose_name='متن پاسخ')),
                ('AnswerImage', models.ImageField(blank=True, null=True, upload_to='answer_images/', verbose_name='تصویر پاسخ')),
                ('IsGraded', models.BooleanField(default=False, verbose_name='وضعیت تصحیح')),
                ('GivenScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره اخذ شده')),
                ('SubmittedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ\u200cها',
                'db_table': 'Answers',
                'managed': False,
            },
        ),
    ]
