# Generated by Django 5.2.7 on 2026-03-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Answers', '0002_auto_20260317_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'managed': False},
        ),
    ]
