# Generated by Django 5.2.7 on 2026-03-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه دانشجو')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('student_number', models.CharField(max_length=20, unique=True, verbose_name='شماره دانشجویی')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('password_hash', models.CharField(max_length=255, verbose_name='رمز عبور (هش شده)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('is_logged_in', models.BooleanField(default=False, verbose_name='وضعیت ورود')),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
