# Generated by Django 5.2.7 on 2026-03-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False, 'verbose_name': 'دانشجو', 'verbose_name_plural': 'دانشجویان'},
        ),
        migrations.AlterModelTable(
            name='student',
            table='Students',
        ),
    ]
