# Generated by Django 5.2.7 on 2026-03-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_alter_student_options_alter_student_table'),
        ('Students', '0003_auto_20260317_1622'),
    ]

    operations = [
    ]
