# Generated by Django 5.2.7 on 2026-03-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_merge_20260318_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
