# Generated by Django 5.2.7 on 2026-03-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddressLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه لاگ')),
                ('IPAddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('LogTime', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('Location', models.CharField(blank=True, max_length=200, null=True, verbose_name='موقعیت مکانی')),
            ],
            options={
                'verbose_name': 'لاگ آدرس آیپی',
                'verbose_name_plural': 'لاگ های آدرس آیپی',
                'db_table': 'IPAddressLogs',
                'managed': False,
            },
        ),
    ]
