# Generated by Django 5.2.7 on 2026-03-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabSwitchLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه لاگ')),
                ('EventTime', models.DateTimeField(auto_now_add=True, verbose_name='زمان رویداد')),
                ('EventType', models.SmallIntegerField(blank=True, null=True, verbose_name='نوع رویداد')),
                ('Duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان')),
            ],
            options={
                'verbose_name': 'لاگ تغییر تب',
                'verbose_name_plural': 'لاگ های تغییر تب',
                'db_table': 'TabSwitchLogs',
                'managed': False,
            },
        ),
    ]
