# Generated by Django 5.2.7 on 2026-03-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TabSwitchLogs', '0002_auto_20260318_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabswitchlog',
            options={'managed': False},
        ),
    ]
