# Generated by Django 5.2.7 on 2026-03-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionViewLog',
            fields=[
                ('ViewLogID', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه لاگ')),
                ('ViewStartTime', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع بازدید')),
                ('ViewEndTime', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان بازدید')),
                ('Duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان')),
            ],
            options={
                'verbose_name': 'لاگ بازدید',
                'verbose_name_plural': 'لاگ های بازدید',
                'db_table': 'QuestionViewLogs',
                'managed': False,
            },
        ),
    ]
