# Generated by Django 5.2.7 on 2026-03-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionViewLogs', '0002_auto_20260319_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionviewlog',
            options={'managed': False},
        ),
    ]
