# Generated by Django 5.2.7 on 2026-03-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('ExamID', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه امتحان')),
                ('Title', models.CharField(max_length=200, verbose_name='عنوان امتحان')),
                ('StartTime', models.DateTimeField(verbose_name='زمان شروع')),
                ('EndTime', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('TotalScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره کل')),
            ],
            options={
                'db_table': 'exams',
                'managed': False,
            },
        ),
    ]
