# Generated by Django 5.2.7 on 2026-03-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه استاد')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('password_hash', models.CharField(max_length=255, verbose_name='رمز عبور (هش شده)')),
            ],
            options={
                'db_table': 'teachers',
                'managed': False,
            },
        ),
    ]
