# Generated by Django 5.2.7 on 2026-03-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0002_alter_teacher_options_alter_teacher_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'managed': False, 'verbose_name': 'استاد', 'verbose_name_plural': 'اساتید'},
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='Teachers',
        ),
    ]
