# Generated by Django 5.2.7 on 2026-03-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0003_alter_teacher_options_alter_teacher_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'managed': False},
        ),
    ]
