# Generated by Django 5.2.7 on 2026-03-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه درس')),
                ('CourseName', models.CharField(max_length=100, verbose_name='نام درس')),
                ('CourseCode', models.CharField(max_length=20, unique=True, verbose_name='کد درس')),
                ('Units', models.PositiveSmallIntegerField(verbose_name='تعداد واحد')),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
    ]
