# Generated by Django 5.2.7 on 2026-03-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EduStaff',
            fields=[
                ('EduID', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه آموزش')),
            ],
            options={
                'db_table': 'EduStaffs',
                'managed': False,
            },
        ),
    ]
