# Generated by Django 5.2.7 on 2026-03-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('ResultID', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه نتیجه')),
                ('TotalScore', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='نمره کسب شده')),
                ('Status', models.BooleanField(default=True, verbose_name='وضعیت قبولی')),
                ('Grade', models.CharField(max_length=20, verbose_name='سطج بندی نمره')),
                ('CalculatedAt', models.DateTimeField(auto_now_add=True, verbose_name='زمان محاسبه')),
            ],
            options={
                'verbose_name': 'نتیجه امتحان',
                'verbose_name_plural': 'نتایج امتحانات',
                'db_table': 'ExamResults',
                'managed': False,
            },
        ),
    ]
