# Generated by Django 5.2.7 on 2026-03-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResults', '0002_auto_20260319_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresult',
            options={'managed': False},
        ),
    ]
