# Generated by Django 5.2.7 on 2026-03-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('SessionID', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه جلسه')),
                ('LoginTime', models.DateTimeField(blank=True, null=True, verbose_name='زمان ورود')),
                ('LogoutTime', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج')),
                ('IsActive', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
            ],
            options={
                'verbose_name': 'جلسه ورود',
                'verbose_name_plural': 'جلسات ورود',
                'db_table': 'LoginSessions',
                'managed': False,
            },
        ),
    ]
