# Generated by Django 5.2.7 on 2026-03-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentID', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه دانشکده')),
                ('DepartmentName', models.CharField(max_length=100, verbose_name='نام دانشکده')),
                ('Location', models.CharField(blank=True, max_length=200, null=True, verbose_name='موقعیت')),
                ('Phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
    ]
