# Generated by Django 5.2.7 on 2026-03-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='Departments',
        ),
    ]
