# Generated by Django 5.2.7 on 2026-03-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralMetric',
            fields=[
                ('MetricID', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه شاخص')),
                ('TotalTimeSpent', models.PositiveIntegerField(default=0, verbose_name='مجموع زمان صرف شده')),
                ('VisitCount', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد بازدید')),
                ('TabSwitchCount', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تغییر تب')),
                ('CopyPasteCount', models.PositiveSmallIntegerField(default=0, verbose_name='نعداد کپی پیست')),
                ('IdleTime', models.IntegerField(default=0, verbose_name='زمان بی فعالی')),
            ],
            options={
                'verbose_name': 'شاخص رفتاری',
                'verbose_name_plural': 'شاخص های رفتاری',
                'db_table': 'BehavioralMetrics',
                'managed': False,
            },
        ),
    ]
