# Generated by Django 5.2.7 on 2026-03-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('FlagID', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه پرچم')),
                ('Reason', models.TextField(blank=True, null=True, verbose_name='دلیل')),
                ('RiskScore', models.PositiveSmallIntegerField(default=0, verbose_name='امتیاز ریسک')),
                ('Severity', models.CharField(max_length=100, verbose_name='شدت تخلف')),
                ('FlagType', models.TextField(blank=True, null=True, verbose_name='نوع تخلف')),
                ('Status', models.CharField(max_length=100, verbose_name='وضعیت نهایی')),
                ('GeneratedAt', models.DateTimeField(auto_now_add=True, verbose_name='زمان تولید')),
            ],
            options={
                'verbose_name': 'پرچم تقلب',
                'verbose_name_plural': 'پرچم های تقلب',
                'db_table': 'FraudFlags',
                'managed': False,
            },
        ),
    ]
